// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// CloudinaryUploaderInterface is an autogenerated mock type for the CloudinaryUploaderInterface type
type CloudinaryUploaderInterface struct {
	mock.Mock
}

// UploadImage provides a mock function with given fields: fileHeader
func (_m *CloudinaryUploaderInterface) UploadImage(fileHeader *multipart.FileHeader) (string, error) {
	ret := _m.Called(fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader) (string, error)); ok {
		return rf(fileHeader)
	}
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader) string); ok {
		r0 = rf(fileHeader)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*multipart.FileHeader) error); ok {
		r1 = rf(fileHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCloudinaryUploaderInterface creates a new instance of CloudinaryUploaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudinaryUploaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudinaryUploaderInterface {
	mock := &CloudinaryUploaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
